### ISSUE TITLE
NicePyConsole styles

### ISSUE THREAD

**Issue by xtigmh** [Orochimarufan/PythonQt#16]
Hi all!
Anyone know how to set styles(such as autumn, colorful, monokai....) in NicePyConsole. I tried modify PygmentsHighlighter.py, but there is no change!

**Comment by Orochimarufan** [comment]
It should work if you add a style= argument here
https://github.com/Orochimarufan/PythonQt/blob/master/examples/NicePyConsole/PygmentsHighlighter.py#L40

**Comment by xtigmh** [comment]
Thanks!
It works.
self._formatter = HtmlFormatter(style='friendly')
![qq 20160810115315](https://cloud.githubusercontent.com/assets/13674730/17541373/4bbd3aac-5ef1-11e6-8187-cefc0762c88a.png)
