### ISSUE TITLE
How to deal with multiple py files? 

### ISSUE THREAD

**Issue by 461353349** [Orochimarufan/PythonQt#17]
There are two py files is defined in the resources. The 2th file call the 1th file. How to deal with it.

If codes are as followings, No correct result meet.

// evaluate the python script which is defined in the resources
mainModule.evalFile(":writefile.py");
mainModule.evalFile(":GettingStarted.py");

**Comment by Orochimarufan** [comment]
Use the QFile importer and load the non-main scripts with the python import mechanism

See https://github.com/Orochimarufan/PythonQt/blob/master/examples/NicePyConsole/main.cpp#L29

**Comment by 461353349** [comment]
Yes, It is Fine. It can work! Thank you!!!
